version: '3.8'
services:
  app:
    build:
      context: .
      dockerfile: ./path/to/your/Dockerfile
    ports:
      - "8080:8080"
    volumes:
      - E:/Java/IdeaProjects/app/code/app:/project/code/app

